import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';
import type { FixResult } from '@/agents/fixer';
import type { AuditReport } from '@/agents/attacker';
import { supabaseAdmin } from '@/lib/supabase/admin';

export interface OpenFixPrInput {
  installationId: number;
  owner: string;
  repo: string;
  baseBranch: string;
  headSha: string;
  filePath: string;
  vulnerabilityId: string;
  report: AuditReport;
  fix: FixResult;
}

export async function openFixPullRequest(input: OpenFixPrInput) {
  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID!,
      privateKey: process.env.GITHUB_APP_PRIVATE_KEY!,
      installationId: input.installationId,
    },
  });

  const { owner, repo } = input;
  const branchName = `vibeguard/fix-${input.vulnerabilityId.slice(0, 8)}`;

  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: input.headSha,
  });

  const { data: existing } = await octokit.repos.getContent({
    owner,
    repo,
    path: input.filePath,
    ref: branchName,
  });
  if (Array.isArray(existing) || existing.type !== 'file') {
    throw new Error(`Expected file at ${input.filePath}`);
  }

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: input.filePath,
    branch: branchName,
    sha: existing.sha,
    message: `fix(security): ${input.report.findings[0]?.title ?? 'VibeGuard patch'}`,
    content: Buffer.from(input.fix.fixed_source, 'utf8').toString('base64'),
    committer: { name: 'VibeGuard Bot', email: 'bot@vibeguard.dev' },
    author: { name: 'VibeGuard Bot', email: 'bot@vibeguard.dev' },
  });

  const body = renderPrBody(input.report, input.fix);
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    head: branchName,
    base: input.baseBranch,
    title: `[VibeGuard] ${input.report.findings[0]?.title ?? 'Security fix'}`,
    body,
    maintainer_can_modify: true,
  });

  await supabaseAdmin.from('fix_attempts').insert({
    vulnerability_id: input.vulnerabilityId,
    branch_name: branchName,
    pr_number: pr.number,
    pr_url: pr.html_url,
    diff: input.fix.fixed_source,
    fix_narrative: input.fix.fix_narrative,
    model: 'gpt-4o',
    tokens_used: 0,
    status: 'pr_open',
  });

  await supabaseAdmin
    .from('vulnerabilities')
    .update({ status: 'pr_open' })
    .eq('id', input.vulnerabilityId);

  return pr;
}

function renderPrBody(report: AuditReport, fix: FixResult): string {
  const f = report.findings[0];
  if (!f) return fix.fix_narrative;
  return `
## VibeGuard Autonomous Security Patch

**Severity:** \`${f.severity}\` · **Category:** \`${f.category}\` · **CWE:** ${f.cwe ?? 'n/a'}

### How we hacked it
${f.exploit_narrative}

\`\`\`
${f.proof_of_concept}
\`\`\`

### How we fixed it
${fix.fix_narrative}

${fix.summary_bullets.map((b) => `- ${b}`).join('\n')}

---
_Generated by VibeGuard-Red + VibeGuard-Blue. Review the diff before merging._
`.trim();
}
